spring.application.name=pin
server.port=${PORT:8086}


spring.datasource.url=jdbc:postgresql://ep-autumn-bonus-apgew4r3-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ADRu9sIae1cd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true